import type { ProblemFraming, RealityWeights, BiasTerms, CalibrationWeights, FocusedFactors } from './types';

export const defaultProblemFraming: ProblemFraming = {
  problemClarity: 7,
  problemComplexity: 6,
  problemUrgency: 8,
  problemImpact: 7,
  problemMeasurability: 6,
  stakeholderAlignment: 6,
  stakeholderInfluence: 7,
  stakeholderAvailability: 5,
  decisionMakerBuyIn: 8,
  crossFunctionalSupport: 6,
  businessValue: 8,
  strategicAlignment: 7,
  competitiveAdvantage: 6,
  regulatoryRequirements: 5,
  marketTiming: 7,
  dataQualityExpectation: 6,
  analyticsMaturity: 5,
  previousProjectSuccess: 7,
  domainKnowledge: 8,
  hypothesesQuality: 6,
  successMetricsClear: 7,
  baselineEstablished: 5,
  benchmarkAvailable: 6,
  outcomeTraceable: 7,
  valueQuantifiable: 8
};

export const defaultRealityWeights: RealityWeights = {
  layer1: {
    budgetAdequacy: 6,
    timelineRealism: 7,
    teamCapacity: 8,
    skillsAvailability: 7,
    toolsAccess: 8,
    dataAvailability: 8,
    dataQuality: 6,
    dataVolume: 7,
    dataVelocity: 6,
    dataPrivacy: 8,
    priorityLevel: 7,
    resourceCompetition: 5,
    politicalSupport: 6,
    changeReadiness: 5,
    dataLiteracy: 5,
    riskIdentification: 6,
    riskAssessment: 7,
    riskMitigation: 6,
    riskContingencyPlanning: 5,
    riskTolerance: 7
  },
  layer2: {
    computingResources: 7,
    dataInfrastructure: 6,
    securityCompliance: 8,
    scalabilityNeeds: 6,
    integrationComplexity: 5,
    algorithmComplexity: 7,
    modelValidation: 8,
    testingRequirements: 7,
    performanceStandards: 6,
    maintenanceNeeds: 5,
    technicalExpertise: 8,
    domainExpertise: 7,
    collaborationEffectiveness: 6,
    learningAgility: 7,
    qualityStandards: 8
  },
  layer3: {
    organizationalReadiness: 6,
    changeManagement: 5,
    userAdoption: 6,
    trainingRequirements: 7,
    supportStructures: 6,
    processIntegration: 5,
    systemIntegration: 6,
    workflowAlignment: 7,
    governanceFramework: 6,
    complianceRequirements: 8,
    roiPotential: 7,
    valueTimeframe: 6,
    scalabilityPotential: 7,
    sustainabilityFactors: 6,
    competitiveImpact: 7
  }
};

export const defaultBiasTerms: BiasTerms = {
  organizationalCulture: 0.1,
  leadershipStyle: 0.05,
  riskAversion: -0.08,
  innovationAppetite: 0.12,
  pastProjectSuccess: 0.05,
  teamExperience: 0.08,
  domainMaturity: 0.15,
  methodologyFamiliarity: 0.03,
  marketConditions: -0.05,
  competitivePressure: 0.07,
  regulatoryEnvironment: -0.03,
  technologyTrends: 0.06,
  optimismBias: 0.04,
  confirmationBias: -0.06,
  availabilityBias: -0.02,
  anchoringBias: -0.04,
  shortTermPressure: -0.09,
  longTermVision: 0.11,
  resourceScarcity: -0.07,
  strategicAlignment: 0.09
};

export const defaultCalibrationWeights: CalibrationWeights = {
    problem_definition: 1,
    problem_stakeholder: 1,
    problem_business: 1,
    problem_readiness: 1,
    problem_success: 1,
    l1_resource: 1,
    l1_data: 1,
    l1_org: 1,
    l1_risk: 1,
    l2_infra: 1,
    l2_dev: 1,
    l2_team: 1,
    l3_readiness: 1,
    l3_integration: 1,
    l3_value: 1,
    bias_org: 1,
    bias_external: 1,
};

export const defaultFocusedFactors: FocusedFactors = {};